-- =============================================================================
-- 001_permission_levels.sql
-- Extend the permission model from 4 levels to 5:
--
--   old: 1=Admin, 2=Editor, 3=Viewer, 4=Disabled
--   new: 1=Admin, 2=Manager, 3=User, 4=Viewer, 5=Disabled
--
-- Owner remains implicit (cw_devices.user_id / cw_locations.owner_id).
--
-- DATA REMAP (order matters — 4 must be freed before 3 moves into it):
--   permission_level 4 (old Disabled) -> 5 (new Disabled)
--   permission_level 3 (old Viewer)   -> 4 (new Viewer)
--   levels 1 and 2 keep their numbers; level 2 is renamed Editor -> Manager.
--
-- !! RUN THIS DURING THE MAINTENANCE WINDOW, IMMEDIATELY BEFORE DEPLOYING THE
-- !! API RELEASE THAT USES THE NEW THRESHOLDS (read < 5, manage <= 2).
-- !! Old API + new data fails closed (new Viewers briefly lose read access).
-- !! New API + old data would GRANT ACCESS TO DISABLED USERS — never do that.
--
-- The DO block is sentinel-guarded: if level 5 already exists in
-- cw_permission_level_types the remap is skipped, so re-running this script
-- cannot corrupt data (an unguarded second run of "4 -> 5" would disable
-- every remapped Viewer).
-- =============================================================================

BEGIN;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM public.cw_permission_level_types WHERE permission_level_id = 5
    ) THEN
        RAISE NOTICE 'permission_level_id 5 already present — remap already applied, skipping.';
        RETURN;
    END IF;

    -- New catalog row first so FK lookups (if any) and the UI can resolve it.
    -- permission_level_id is GENERATED BY DEFAULT AS IDENTITY, so an explicit
    -- value is allowed; the sequences are resynced right after.
    INSERT INTO public.cw_permission_level_types (permission_level_id, name)
    VALUES (5, 'Disabled');

    PERFORM setval(
        pg_get_serial_sequence('public.cw_permission_level_types', 'permission_level_id'),
        (SELECT max(permission_level_id) FROM public.cw_permission_level_types)
    );
    PERFORM setval(
        pg_get_serial_sequence('public.cw_permission_level_types', 'id'),
        (SELECT max(id) FROM public.cw_permission_level_types)
    );

    -- Remap data: free level 4 before moving level 3 into it.
    UPDATE public.cw_device_owners   SET permission_level = 5 WHERE permission_level = 4;
    UPDATE public.cw_location_owners SET permission_level = 5 WHERE permission_level = 4;

    UPDATE public.cw_device_owners   SET permission_level = 4 WHERE permission_level = 3;
    UPDATE public.cw_location_owners SET permission_level = 4 WHERE permission_level = 3;

    -- Rename catalog entries to the new role names.
    UPDATE public.cw_permission_level_types SET name = 'Admin'   WHERE permission_level_id = 1;
    UPDATE public.cw_permission_level_types SET name = 'Manager' WHERE permission_level_id = 2;
    UPDATE public.cw_permission_level_types SET name = 'User'    WHERE permission_level_id = 3;
    UPDATE public.cw_permission_level_types SET name = 'Viewer'  WHERE permission_level_id = 4;

    RAISE NOTICE 'Permission level remap applied.';
END
$$;

-- Range guards so application bugs can never write a level outside 1..5
-- (permission_level is numeric; also forbid fractional values).
ALTER TABLE public.cw_device_owners
    DROP CONSTRAINT IF EXISTS cw_device_owners_permission_level_range;
ALTER TABLE public.cw_device_owners
    ADD CONSTRAINT cw_device_owners_permission_level_range
    CHECK (permission_level BETWEEN 1 AND 5 AND permission_level = floor(permission_level));

ALTER TABLE public.cw_location_owners
    DROP CONSTRAINT IF EXISTS cw_location_owners_permission_level_range;
ALTER TABLE public.cw_location_owners
    ADD CONSTRAINT cw_location_owners_permission_level_range
    CHECK (
        permission_level IS NULL
        OR (permission_level BETWEEN 1 AND 5 AND permission_level = floor(permission_level))
    );

COMMIT;

-- Post-check: distributions should show levels only in 1..5 and the catalog
-- should read 1=Admin, 2=Manager, 3=User, 4=Viewer, 5=Disabled.
SELECT * FROM public.cw_permission_level_types ORDER BY permission_level_id;
SELECT 'cw_device_owners' AS tbl, permission_level, count(*)
FROM public.cw_device_owners GROUP BY permission_level
UNION ALL
SELECT 'cw_location_owners', permission_level, count(*)
FROM public.cw_location_owners GROUP BY permission_level
ORDER BY tbl, permission_level;
